from telegram import InlineKeyboardButton, InlineKeyboardMarkup
def main_menu_keyboard():
    return InlineKeyboardMarkup([[InlineKeyboardButton('Лиды',callback_data='leads:list'),InlineKeyboardButton('Аналитика',callback_data='analytics:menu')],[InlineKeyboardButton('Запустить поиск',callback_data='hunt:menu'),InlineKeyboardButton('Outreach',callback_data='outreach:menu')],[InlineKeyboardButton('Market AI',callback_data='market:menu'),InlineKeyboardButton('Content AI',callback_data='content:menu')],[InlineKeyboardButton('Proposals',callback_data='proposal:list')]])
def leads_list_keyboard(leads):
    rows=[[InlineKeyboardButton(f"#{l['id']} | {l['score']} | {l['title'][:35]}",callback_data=f"lead:view:{l['id']}")] for l in leads[:10]]; rows.append([InlineKeyboardButton('Назад',callback_data='menu')]); return InlineKeyboardMarkup(rows)
def lead_card_keyboard(lead_id:int):
    return InlineKeyboardMarkup([[InlineKeyboardButton('Contacted',callback_data=f'lead:status:{lead_id}:contacted'),InlineKeyboardButton('Qualified',callback_data=f'lead:status:{lead_id}:qualified')],[InlineKeyboardButton('Proposal Sent',callback_data=f'lead:status:{lead_id}:proposal_sent'),InlineKeyboardButton('Lost',callback_data=f'lead:status:{lead_id}:lost')],[InlineKeyboardButton('Email Outreach',callback_data=f'outreach:generate:{lead_id}:email'),InlineKeyboardButton('LinkedIn Outreach',callback_data=f'outreach:generate:{lead_id}:linkedin')],[InlineKeyboardButton('Создать КП',callback_data=f'proposal:generate:{lead_id}')],[InlineKeyboardButton('Назад',callback_data='leads:list')]])
def hunt_menu_keyboard(): return InlineKeyboardMarkup([[InlineKeyboardButton('USA AI Automation',callback_data='hunt:run:AI software automation:USA')],[InlineKeyboardButton('Europe Outsourcing',callback_data='hunt:run:software outsourcing:Europe')],[InlineKeyboardButton('UAE AI Projects',callback_data='hunt:run:AI development automation:UAE')],[InlineKeyboardButton('Назад',callback_data='menu')]])
def outreach_menu_keyboard(): return InlineKeyboardMarkup([[InlineKeyboardButton('Создать базовую кампанию',callback_data='outreach:create_default')],[InlineKeyboardButton('Последние сообщения',callback_data='outreach:sequences')],[InlineKeyboardButton('Назад',callback_data='menu')]])
def market_menu_keyboard(): return InlineKeyboardMarkup([[InlineKeyboardButton('Создать USA AI Watch',callback_data='market:create:usa_ai')],[InlineKeyboardButton('Топ сигналы',callback_data='market:signals')],[InlineKeyboardButton('Назад',callback_data='menu')]])
def content_menu_keyboard(): return InlineKeyboardMarkup([[InlineKeyboardButton('Создать контент-план',callback_data='content:create_plan')],[InlineKeyboardButton('LinkedIn пост',callback_data='content:generate:linkedin_post')],[InlineKeyboardButton('Short video script',callback_data='content:generate:short_video_script')],[InlineKeyboardButton('Case study',callback_data='content:generate:case_study')],[InlineKeyboardButton('Последние материалы',callback_data='content:items')],[InlineKeyboardButton('Назад',callback_data='menu')]])
def analytics_menu_keyboard(): return InlineKeyboardMarkup([[InlineKeyboardButton('Pipeline Summary',callback_data='analytics:summary')],[InlineKeyboardButton('AI Recommendations',callback_data='analytics:recommendations')],[InlineKeyboardButton('Management Report',callback_data='analytics:report')],[InlineKeyboardButton('Назад',callback_data='menu')]])
